### ISSUE TITLE
switching text around doesn't work

### ISSUE THREAD

**Issue by cosmicexplorer** [cosmicexplorer/imposters#7]
``` json
...
 {
  "pattern": "Israel",
  "replacement": {
    "text": "Pales‌tine"
  }
}, {
  "pattern": "Palestine",
  "replacement": {
    "text": "Isr‌ael"
  }
},
...
```

This bit had been in there for a while in various states of nonfunctionality; I've removed it (along with Bernie<->Hillary, etc) because it seems chrome automatically changed zero-width non-joiners to capitalizing the next word (which might be a standard or something, idk). What would be better would be to add an extra field to the replacements objects to specify strings of text (or regexen) to avoid modification. Wish this could just be easier and we could drop in zero-width spaces or whatever, but chrome seems to be resistant. Oh well.

**Comment by ikeadrift** [comment]
foolish chrome. bend to our will

**Comment by ambuc** [comment]
@cosmicexplorer one thing you could do for "satire" is just put scare quotes around these things. replace Israel with "Palestine" and Palestine with "Israel". Would that work?

**Comment by cosmicexplorer** [comment]
We'd need to refactor the replacements format so that it excludes words
with quotes around it, or something, because quotes are counted as word
boundaries so even adding `"fullWord": true` would still cycle between the
two endlessly.

I tried padding it with null chars but javascript doesn't allow that for
some reason so I think the best way is to insert some unicode marker (kind
of like with [zalgify](https://github.com/cosmicexplorer/zalgify) into the
middle of the replacement text (possibly a zero-width space?) so that the
match fails after the replacement occurs, and cyclical replacements work.

The only problem is that zero-width spaces will allow word wrapping at the
site of the space, which we don't want, so we'd have to find the right
unicode character that will break the regex match, but not be visible, and
not allow word wrapping.

**Comment by cosmicexplorer** [comment]
Also, my fat fingers just deleted your comment which was SUPER rude so I'm very sorry about that. I wish github had a way to fix that. For those concerned the comment was:

@ambuc:
 @cosmicexplorer one thing you could
 do for "satire" is just put scare quotes around these things. replace
 Israel with "Palestine" and Palestine with "Israel". Would that work?

**Comment by ambuc** [comment]
@cosmicexplorer you could use the classic non-breaking zero-width joiner? http://www.fileformat.info/info/unicode/char/feff/index.htm
&#xfeff;

**Comment by cosmicexplorer** [comment]
how could i have forgotten the fundamentals????? let's try that

**Comment by cosmicexplorer** [comment]
forgot that github has that keyword to close pr thing, let's see if this works

**Comment by cosmicexplorer** [comment]
Yep, that's the problem. See 
![2016-01-07-051024_1920x1080_scrot](https://butt.githubusercontent.com/assets/1305167/12167925/0e936852-b4fd-11e5-962e-5d4d373737e7.png).

It capitalizes the following word, since it's technically a spaaace. This is what tripped me up last time we tried this.

**Comment by ambuc** [comment]
@cosmicexplorer try a joiner, they're meant to go in-between words that can't break, without capitalization http://www.fileformat.info/info/unicode/char/2060/index.htm

**Comment by cosmicexplorer** [comment]
More failures.

![2016-01-07-135015_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1305167/12179594/c1b1ad02-b545-11e5-881f-8da7fc8075d1.png)

I'm gonna research why this happens. It doesn't appear to be some custom javascript recapitalizing everything;

WAIT I'M AN IDIOT IT'S BECAUSE OF THE CAPITALIZATION THING I'LL FIX THAT

Basically, it's because of the way we're handling capitalization. Take a look at this [if-else chain](https://github.com/cosmicexplorer/imposters/blob/a9c3255649db1b8b8efa803263bbf129528027c2/common/replace-all.coffee#L12); we attempt to respect (in a hacked and silly, but simple and robust way) the capitalization of the original text: all caps, all lowercase, or title case, unless `strictCaps` is on, in which case we just output the text literally. Because names and places are proper nouns, they're initially capitalized, and so this code interprets the text as title-case; then, when we insert a space in the replacement, this code interprets that as a new word and capitalizes it.

Unfortunately, this will require updating the extension; less unfortunately, this is an easy fix. I think all we need to do is replace the the `/\b./g` regex with something that doesn't count whatever unicode character we use as a zero width joiner. Maybe literally:

``` coffeescript
text.replace /(\s|^)(.)/g, (match, g1, g2) ->
  g1 + (if g1 isnt '\u2060' then g2.toUpperCase() else g2)
```

I'm on it.

**Comment by cosmicexplorer** [comment]
^that change worked first try and I just didn't apply it for exactly a full calendar year, does that make me punctual? Anyway, this totally works (see 5865426d6a74fded7ea607926b490353ab7ab974).

![2017-01-06-011027_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1305167/21709194/2b3aa9f0-d3ad-11e6-8c1c-a06129c82eca.png)
